sudo: true
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
jobs:
  include:
    - stage: lint
      python: 3.6
      script:
          - pip install tox-travis codacy-coverage pre-commit
          - bash bin/versionCheck.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
          - pre-commit run --verbose --all-files
          - tox -e lint
    - stage: test
      script:
        - pip install tox-travis codacy-coverage pre-commit
        - tox
    - stage: deploy
      python: 3.6
      script:
        - sed --expression "s|GIT_HASH|$TRAVIS_COMMIT|g" --in-place **/version.py
      deploy:
        provider: pypi
        user: $PYPI_USER
        password: $PYPI_PASSWORD
        on:
          branch: master
    - stage: after_success
      script:
        - python-codacy-coverage -r reports/coverage.xml
